apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  APP_COLOR: {{ .Values.config.appColor }}
  WELCOME_MESSAGE: {{ .Values.config.welcomeMessage }}